module.exports = {
  general: 'Terjadi kesalahan sistem',
  auth: 'Session anda telah habis, silahkan login kembali',
  message: 'message',
  validation: 'validation',
  permission: 'Tidak memiliki hak akses untuk fitur ini',
  invalid_request: 'Permintaan tidak valid',
  email_required: 'Email wajib diisi',
  email_format: 'Email tidak valid',
  email_already_registered: 'Email yang anda masukkan sudah terdaftar, silahkan coba email lain',
  password_required: 'Password wajib diisi',
  password_min_max_length: 'Password minimal 6 karakter / digit',
  password_format: 'Password wajib alfanumerik (contoh : asd123)',
  password_match: 'Password dan konfirmasi password tidak sesuai',
  password_wrong: 'Password yang anda masukkan salah',
  confirmation_password_required: 'Konfirmasi password wajib diisi',
  register_failed: 'Proses registrasi gagal, silahkan coba beberapa saat lagi',
  user_not_found: 'User tidak terdaftar',
  user_suspend: 'Akun ini telah disuspend, silahkan hubungi admin',
  nomor_id_format: 'Nomor ID wajib angka',
  nama_lengkap_required: 'Nama lengkap wajib diisi (sesuai ktp)',
  nama_lengkap_format: 'Nama lengkap wajib huruf',
  nama_panggilan_required: 'Nama panggilan wajib diisi',
  nama_panggilan_format: 'Nama panggilan wajib huruf',
  tanggal_lahir_required: 'Tanggal lahir wajib diisi',
  tanggal_lahir_date_format: 'Tanggal lahir tidak valid',
  alamat_ktp_required: 'Alamat wajib diisi (sesuai ktp)',
  alamat_format: 'Alamat format tidak valid',
  kota_domisili_required: 'Kota wajib diisi',
  provinsi_domisili_required: 'Provinsi wajib diisi',
  pekerjaan_required: 'Pekerjaan wajib diisi',
  nomor_telepon_required: 'Nomor telepon yang bisa dihubungi wajib diisi',
  nomor_telepon_required: 'Nomor telepon yang bisa dihubungi wajib diisi',
  nomor_telepon_telegram_required: 'Nomor telepon telegram wajib diisi',
  nomor_telepon_whatsapp_required: 'Nomor telepon whatsapp wajib diisi',
  nomor_telepon_emergency_required: 'Nomor telepon emergency wajib diisi',
  nomor_08: 'Nomor telepon wajib nomor indonesia (dimulai dengan 08)',
  nomor_telepon_min_max: 'Nomor telepon minimal 10 digit dan maksimal 14 digit',
  nomor_telepon_format: 'Nomor telepon tidak valid (wajib angka)',
  golongan_darah_required: 'Golongan darah wajib dipilih',
  golongan_darah_enum: 'Golongan darah tidak valid',
  informasi_wali_required: 'Informasi ewali wajib dipilih salah satu',
  informasi_wali_format: 'Informasi tidak valid',
  snk_required: "Syarat dan ketentuan wajib disetujui",
  snk_format: "Syarat dan ketentuan tidak valid",
  snk_must_accepted: 'Syarat dan ketentuan wajib disetujui',
  emoney_required: 'E-money wajib dipilih',
  emoney_not_valid: 'E-money tidak valid',
  kota_required: 'Nama kota wajib diisi',
  kota_format: 'Nama kota tidak valid',
  kota_exist: 'Nama kota sudah terdaftar, silahkan daftar kota lain',
  create_kota_failed: 'Gagal membuat kota, silahkan coba beberapa saat lagi',
  kota_not_exist: 'Kota tidak terdaftar',
  note_required: 'Catatan wajib diisi',
  status_form_required: 'Status terima / tolak form wajib dipilih',
  update_status_failed: 'Update status gagal, silahkan coba beberapa saat lagi',
  user_not_submit_form_yet: 'User ini belum submit form',
  user_still_pending: 'User upgrade / downgrade hanya user dengan status aktif / suspend',
  // stack
  stack_invalid_data_register: 'Data register tidak valid',
  stack_email_already_registered: 'Email sudah terdaftar',
  stack_register_failed: 'Register gagal, database error',
  stack_user_not_found: 'User tidak terdaftar',
  stack_user_suspend: 'Akun ini telah disuspend',
  stack_password_wrong: 'Password yang anda masukkan salah',
  stack_invalid_data_submit_form: 'Data detail user tidak valid',
  stack_resend_email: 'Email tidak valid',
  stack_permission_must_admin: 'User login harus admin / ketua chapter',
  stack_create_kota_chapter: 'Data kota tidak valid',
  stack_kota_exist: 'Kota sudah terdaftar',
  stack_create_kota_failed: 'Gagal membuat kota, error database',
  stack_kota_not_exist: 'Kota yang dimasukkan tidak terdaftar',
  stack_invalid_update_kota: 'Parameter kota id dibutuhkan',
  stack_forbidden: 'Tidak diperbolehkan untuk mengedit diri sendiri',
  stack_invalid_parameter: 'Parameter param dibutuhkan',
  stack_invalid_body: 'Parameter body dibutuhkan',
  stack_admin_cannot_upgrade: 'Admin adalah role yang paling tinggi',
  update_role_failed: 'Update role gagal, silahkan coba beberapa saat lagi',
  stack_update_role_failed: 'Update role gagal, error database',
  stack_note_required: 'Note wajib diisi jika form direject',
  status_form_invalid: 'Wajib memilih status form (terima / tolak)',
  stack_invalid_data_approve_reject_form: 'Data approve / reject form tidak valid',
  stack_update_status_failed: 'Update status user gagal, error database',
  stack_user_not_submit_form_yet: 'User ini belum submit form',
  stack_kota_required: 'Kota untuk user wajib dipilih sebelum diapprove',
  stack_user_still_pending: 'Jika ingin mengupgrade / downgrade user, statusnya harus != 3 (pending)'
}